#!/bin/bash


file="${1}"
command="${2}"
theme_rows="${3}"
i="${theme_rows}"

_find_start(){
	i_max="2"
	while [[ "${i}" -ge "${i_max}" ]]; do
		let 'i--'
		if [[ `sed -n "${i}"p "${file}"` =~ "Package: " ]]; then
			_rows="${i}"
			i="0"
		fi
	done
}

_find_end(){
	i_max="$((${i}+${i}))"
	while [[ "${i}" -le "${i_max}" ]]; do
		let 'i++'
		if [[ `sed -n "${i}"p "${file}"` == "" ]]; then
			_rows="${i}"
			i="$((${i_max}+1))"
		fi
	done
}

case "${command}" in
	start)
		_find_start
	;;
	end)
		_find_end
	;;
esac
echo "${_rows}"
