#!/bin/bash


if [[ "${0}" =~ "/" ]]; then
	cd "${0%/*}"
fi

_do(){
	sed -i. '/Depiction: /d' "${aaa}"
	sed -i. '/homepage: /d' "${aaa}"
	sed -i. '/Website: /d' "${aaa}"
	sed -i. '/Installed-Size: /d' "${aaa}"
	sed -i. '/MD5sum: /d' "${aaa}"
	sed -i. '/sileodepiction: /d' "${aaa}"
	sed -i. '/Sponsor: /d' "${aaa}"
	sed -i. '/Icon: /d' "${aaa}"
	sed -i. '/Tag: /d' "${aaa}"
	sed -i. '/dev: /d' "${aaa}"
	sed -i. 's/BigBoss <bigboss@thebigboss.org>/null/g' "${aaa}"
	rm -rf "${aaa}."
}


for aaa in "${@}"; do
	unset size_0
	unset size_1
	size_0=`du -h "${aaa}" | sed "s#	${aaa}##g"`
	starttime=`date +%s`
	_do
	endtime=`date +%s`
	sumtime=$[ ${endtime} - ${starttime} ]
	size_1=`du -h "${aaa}" | sed "s#	${aaa}##g"`
	aaa="${aaa##*/}"
	echo -n "${aaa}: "
	echo "${size_0} ---> ${size_1}		Used ${sumtime} seconds"
done
