#!/bin/bash


i_max='8'

if [[ "${0}" =~ "/" ]]; then
	cd "${0%/*}"
fi

_do(){
	i='1'
	while [[ "${i}" -le "${i_max}" ]]; do
		let 'i++'
		bbb=`grep -n "Section: ${_find_text}" "${aaa}" | sed -n '1p'`
		bbb="${bbb%%:*}"
		if [[ ! "${bbb}" ]]; then
			echo "no ${_find_text}"
			i="$((${i_max}+1))"
		else
			_start=`./find "${aaa}" "start" "${bbb}"`
			_end=`./find "${aaa}" "end" "${bbb}"`
			echo -n "found: ${bbb}"...
			echo -n "		delete: "
			echo -n "${_start}"...
			echo "${_end}"...
			sed -i. "${_start}","${_end}"d "${aaa}"
			unset _start
			unset _end
			i=1
		fi
		rm -rf "${aaa}."
	done
	unset _find_text
}

_run(){
	_find_text='Addons'
	_do
	_find_text='Ringtones'
	_do
	_find_text='Theme'
	_do
	_find_text='BossPaper Addons'
	_do
	_find_text='Java'
	_do
	_find_text='Wallpaper'
	_do
	_find_text='SBSettings Addons'
	_do
	_find_text='Font'
	_do
	_find_text='font'
	_do
	_find_text='Messaging'
	_do
	_find_text='Game'
	_do
	_find_text='Toy'
	_do
	_find_text='Soundboards'
	_do
	_find_text='Hunspell_Dictionaries'
	_do
	_find_text='Entertainment'
	_do
	_find_text='Multimedia'
	_do
	_find_text='Navigation'
	_do
	_find_text='Applications (Addons)'
	_do
	_find_text='Eduvation'
	_do
	_find_text='Site-Specific Apps'
	_do
	_find_text='Localization'
	_do
	_find_text='App Addons'
	_do
	_find_text='Social'
	_do
	_find_text='Carrier Bundles'
	_do
	_find_text='Productivity'
	_do
	_find_text='Education'
	_do
	_find_text='Cydgets'
	_do
	_find_text='Cydgets'
	_do
}


for aaa in "${@}"; do
	unset size_0
	unset size_1
	size_0=`du -h "${aaa}" | sed "s#	${aaa}##g"`
	starttime=`date +%s`
	_run
	endtime=`date +%s`
	sumtime=$[ ${endtime} - ${starttime} ]
	size_1=`du -h "${aaa}" | sed "s#	${aaa}##g"`
	aaa="${aaa##*/}"
	echo "Enjoy"
	echo -n "${aaa}: "
	echo "${size_0} ---> ${size_1}		Used ${sumtime} seconds"
done
