#!/bin/bash


aaa="${1}"
echo -n 'file size: '
echo `du -h "${aaa}" | sed "s#${aaa}##g"`
echo -n 'Streamlining'
sed -i. '/Depiction: /d' "${1}"
echo -n '.'
sed -i. '/homepage: /d' "${1}"
echo -n '.'
sed -i. '/Website: /d' "${1}"
echo -n '.'
sed -i. '/Installed-Size: /d' "${1}"
echo -n '.'
sed -i. '/sileodepiction: /d' "${1}"
echo -n '.'
sed -i. '/Sponsor: /d' "${1}"
echo -n '.'
rm -rf "${1}."
echo 'OK!'
echo -n 'now file size: '
echo `du -h "${aaa}" | sed "s#${aaa}##g"`
